### ISSUE TITLE
Chamfer/Fillet/Union/Difference unexpected behavior

### ISSUE THREAD

**Issue by Billiam** [zalo/CascadeStudio#119]
This may just be my misunderstanding, but I'm running into a couple of issues related to chamfers and fillets:

[Example](https://zalo.github.io/CascadeStudio/?code=fZJfa4MwFMXf8ykufYqQgUk21zHKYNJ9gu1JfEjddZWmCmqhUPrdd6PWP3RLSF5yfud6PMRiC1l13BUlwgbiPWaHXXXmq7i%2Fe1sJyI1tMGDMEtqc6txkKIl9JywKBUg6j2HwOtcV6Z%2B1KRtrWuTJmhC3UzEOENDWJ1y69NIlI4%2BNxXtzzLHefv9gwyeZduICCVgLeEnH9B%2BFpS8taNVnT8iiBTwJePbi2oP%2FFUaPYWSXhxwRmSiVG5Que6XOb50qcvQnYMP1rBSnPMhwGOH0u0H%2Fl9%2FjXYM32NP5nGZFDnx4JwFcGND6Kouq5MnUvTNM%2F3WPqA5RPkR3iJ6Q6y8%3D&gui=q1ZKzs8tyM9LzSvxS8xNVbJSSk4sTk5MSQ3LTC1X0lHyTS3OCEotVrIy0DOE84IS89KBSqMN9AwMdYxidZScE5MzUu2VrNISc4pTdZSCElMyS4F6jA1gbJgOIwMdEwOgBte89KLEMpCWkqJSoA7n%2FNykzDy4EbUA)

When applying a chamfer to one or more already-filleted edges, the edge which will be chamfered is unpredictable and doesn't respect the selected edge(s), _and_ then the filleted edge reappears.

When a shape with a chamfer is Unioned or Differenced with anything else (including just `Union([self])`), the previously chamfered edges reappear in place.

**Comment by raydeleu** [comment]
I think you have to redefine the variable in which you declare the shape, so for example: 

surface2 = FilletEdges(surface2, 10, [1, 3, 5, 7], false)

instead of using only the FilletEdges command. Once you do that, it seems to work correctly. It could be that by just performing the function you only adapt the displayed object, not the named object.
