### ISSUE TITLE
emm..

### ISSUE THREAD

**Issue by Johnly1986** [zalo/CascadeStudio#2]
How to run it.

**Comment by zalo** [comment]
There are no builds; everything is statically linked assets (I’ll probably move to modules at some point).

I usually just use `live-server` in the root directory.
VS Code’s Live Server extension also works well.

Intellisense may require a copy of the .d.ts files to be copied into a CascadeStudio directory system beneath the main CascadeStudio directory structure (just due to how the GitHub.io domain stuff works relative to the live server domain stuff).  A lazy hack until I start supporting running locally properly.
